# Generated by Django 3.0.7 on 2020-06-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cheading0',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blog',
            name='cheading1',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blog',
            name='cheading2',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
